### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by dnkennedy**
Add https://github.com/ReproNim/fsl_seg_to_nidm/archive/refs/heads/master.zip to get fslsegstats2nidm installed

### CODE REVIEW

**Comment by dnkennedy** [comment]
Would love a sanity check from @satra

**Comment by satra** [comment]
@dnkennedy - looks good, but this should be in the repronim/reprohub repo. also you could add `'rdflib>=6.1.0'` to ensure that version is picked up.

**Comment by satra** [comment]
closing this. applied to repronim repo.

**Comment by dnkennedy** [comment]
oops, wrong repo...

**Pull request closed without merging**
